version: '3.8'

services:
  signature-generator:
    build: .
    container_name: signature-generator-innovate
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - signature-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.signature.rule=Host(`signature.local`)"
      - "traefik.http.services.signature.loadbalancer.server.port=80"

networks:
  signature-network:
    driver: bridge