version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: firma-digital-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: firma-digital-backend
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - LOGO_URL=http://backend:3000/assets/images/logo-innovate.png
      - PHONE_ICON_URL=http://backend:3000/assets/images/icon-phone.png
      - MOBILE_ICON_URL=http://backend:3000/assets/images/icon-mobile.png
      - EMAIL_ICON_URL=http://backend:3000/assets/images/icon-email.png
      - WEB_ICON_URL=http://backend:3000/assets/images/icon-web.png
      - FACEBOOK_ICON_URL=http://backend:3000/assets/images/icon-facebook.png
      - INSTAGRAM_ICON_URL=http://backend:3000/assets/images/icon-instagram.png
      - LINKEDIN_ICON_URL=http://backend:3000/assets/images/icon-linkedin.png
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend/assets:/app/assets
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: firma-digital-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: