version: '3.8'

services:
  signature-generator:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: signature-generator-app
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - signature-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  signature-network:
    driver: bridge